// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeCalculation.Persistence;

#nullable disable

namespace TimeCalculation.Persistence.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260803193503_AddPayrollExportConfig")]
    partial class AddPayrollExportConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeCalculation.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.DifferentialRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("integer")
                        .HasColumnName("adjustment_type");

                    b.Property<decimal>("AdjustmentValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("adjustment_value");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("DayOfWeekRangeEnd")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week_range_end");

                    b.Property<int>("DayOfWeekRangeStart")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week_range_start");

                    b.Property<int>("DayScheduleMode")
                        .HasColumnType("integer")
                        .HasColumnName("day_schedule_mode");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("days_of_week");

                    b.Property<string>("ExclusivityGroup")
                        .HasColumnType("text")
                        .HasColumnName("exclusivity_group");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MinHoursInRange")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("min_hours_in_range");

                    b.Property<decimal>("MinHoursInWindow")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("min_hours_in_window");

                    b.Property<string>("SpecificDates")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specific_dates");

                    b.Property<LocalTime>("WindowEnd")
                        .HasColumnType("time")
                        .HasColumnName("window_end");

                    b.Property<LocalTime>("WindowStart")
                        .HasColumnType("time")
                        .HasColumnName("window_start");

                    b.HasKey("Id")
                        .HasName("pk_differential_rules");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_differential_rules_client_id");

                    b.ToTable("differential_rules", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("HomeTimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_time_zone_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<decimal>("MinimumWage")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("minimum_wage");

                    b.Property<string>("PostNominalLetters")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_nominal_letters");

                    b.Property<string>("Salutation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_employees_client_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.HolidayCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Dates")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dates");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_holiday_calendars");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_holiday_calendars_client_id");

                    b.ToTable("holiday_calendars", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.PayRules.PayRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDifferentialCodes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("active_differential_codes");

                    b.Property<string>("ActivePremiumCodes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("active_premium_codes");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("DistanceBetweenShiftsHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("distance_between_shifts_hours");

                    b.Property<LocalDate?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int>("ExpectedBreakLengthMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("expected_break_length_minutes");

                    b.Property<int>("ExpectedLunchLengthMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("expected_lunch_length_minutes");

                    b.Property<int?>("HolidayCalendarId")
                        .HasColumnType("integer")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MaxShiftLengthHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("max_shift_length_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<LocalDate>("PayPeriodAnchor")
                        .HasColumnType("date")
                        .HasColumnName("pay_period_anchor");

                    b.Property<int>("PayPeriodFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("pay_period_frequency");

                    b.Property<decimal>("PunchPairResetHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("punch_pair_reset_hours");

                    b.Property<int>("RuleFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("rule_family_id");

                    b.Property<int>("ShiftDateStrategy")
                        .HasColumnType("integer")
                        .HasColumnName("shift_date_strategy");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TemplateCode")
                        .HasColumnType("text")
                        .HasColumnName("template_code");

                    b.Property<int?>("TemplateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("template_version");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("WorkweekStartDay")
                        .HasColumnType("integer")
                        .HasColumnName("workweek_start_day");

                    b.HasKey("Id")
                        .HasName("pk_pay_rules");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_pay_rules_client_id");

                    b.HasIndex("HolidayCalendarId")
                        .HasDatabaseName("ix_pay_rules_holiday_calendar_id");

                    b.HasIndex("RuleFamilyId")
                        .HasDatabaseName("ix_pay_rules_rule_family_id");

                    b.ToTable("pay_rules", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("base_rate");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_positions_client_id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Premiums.ClientPremiumPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<string>("PremiumCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("premium_code");

                    b.Property<Instant>("SetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_at");

                    b.Property<string>("SetBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_by");

                    b.Property<int>("WaiverPolicy")
                        .HasColumnType("integer")
                        .HasColumnName("waiver_policy");

                    b.HasKey("Id")
                        .HasName("pk_client_premium_policies");

                    b.HasIndex("ClientId", "PremiumCode", "EffectiveFrom")
                        .HasDatabaseName("ix_client_premium_policies_client_id_premium_code_effective_fr");

                    b.ToTable("client_premium_policies", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Punch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<int?>("BonusKind")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_kind");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<bool>("CountsTowardRegularRate")
                        .HasColumnType("boolean")
                        .HasColumnName("counts_toward_regular_rate");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("DevicePunchId")
                        .HasColumnType("text")
                        .HasColumnName("device_punch_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<decimal?>("Hours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("hours");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("import_batch_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<Instant>("PunchTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("punch_time");

                    b.Property<string>("PunchTimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("punch_time_zone_id");

                    b.Property<Instant?>("RoundedPunchTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rounded_punch_time");

                    b.Property<int?>("Subtype")
                        .HasColumnType("integer")
                        .HasColumnName("subtype");

                    b.HasKey("Id")
                        .HasName("pk_punches");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_punches_import_batch_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_punches_position_id");

                    b.HasIndex("ClientId", "EmployeeId", "PunchTime")
                        .HasDatabaseName("ix_punches_client_id_employee_id_punch_time");

                    b.HasIndex("EmployeeId", "DeviceId", "DevicePunchId")
                        .IsUnique()
                        .HasDatabaseName("ix_punches_employee_id_device_id_device_punch_id");

                    b.ToTable("punches", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.PunchAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("text")
                        .HasColumnName("previous_values");

                    b.Property<int>("PunchId")
                        .HasColumnType("integer")
                        .HasColumnName("punch_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_punch_audits");

                    b.HasIndex("ClientId", "PunchId")
                        .HasDatabaseName("ix_punch_audits_client_id_punch_id");

                    b.ToTable("punch_audits", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.StateMinimumWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_state_minimum_wages");

                    b.HasIndex("State", "EffectiveFrom")
                        .HasDatabaseName("ix_state_minimum_wages_state_effective_from");

                    b.ToTable("state_minimum_wages", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.AppUser", b =>
                {
                    b.Property<string>("CognitoSub")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cognito_sub");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("CognitoSub")
                        .HasName("pk_app_users");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_app_users_client_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_app_users_employee_id");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.ClientSettings", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<bool>("RequirePunchEditApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("require_punch_edit_approval");

                    b.Property<bool>("ShowFullPayItemizationToEmployees")
                        .HasColumnType("boolean")
                        .HasColumnName("show_full_pay_itemization_to_employees");

                    b.HasKey("ClientId")
                        .HasName("pk_client_settings");

                    b.ToTable("client_settings", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.EmployeePositionAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("rate");

                    b.HasKey("Id")
                        .HasName("pk_employee_position_assignments");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_position_assignments_employee_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_employee_position_assignments_position_id");

                    b.HasIndex("ClientId", "EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("ix_employee_position_assignments_client_id_employee_id_effecti");

                    b.ToTable("employee_position_assignments", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayRuleAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("PayRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("pay_rule_id");

                    b.HasKey("Id")
                        .HasName("pk_pay_rule_assignments");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_pay_rule_assignments_employee_id");

                    b.HasIndex("PayRuleId")
                        .HasDatabaseName("ix_pay_rule_assignments_pay_rule_id");

                    b.HasIndex("ClientId", "EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("ix_pay_rule_assignments_client_id_employee_id_effective_from");

                    b.ToTable("pay_rule_assignments", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayrollEarningCodeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EarningCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("earning_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_code");

                    b.Property<int>("LineType")
                        .HasColumnType("integer")
                        .HasColumnName("line_type");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<int>("ValueBasis")
                        .HasColumnType("integer")
                        .HasColumnName("value_basis");

                    b.HasKey("Id")
                        .HasName("pk_payroll_earning_code_mappings");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_payroll_earning_code_mappings_profile_id");

                    b.HasIndex("ClientId", "ProfileId")
                        .HasDatabaseName("ix_payroll_earning_code_mappings_client_id_profile_id");

                    b.HasIndex("ClientId", "ProfileId", "LineType", "LineCode")
                        .IsUnique()
                        .HasDatabaseName("ix_payroll_earning_code_mappings_client_id_profile_id_line_typ")
                        .HasFilter("is_deleted = false");

                    b.ToTable("payroll_earning_code_mappings", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayrollEmployeeIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("ExternalEmployeeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_employee_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_payroll_employee_identifiers");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_payroll_employee_identifiers_employee_id");

                    b.HasIndex("ClientId", "ProfileId")
                        .HasDatabaseName("ix_payroll_employee_identifiers_client_id_profile_id");

                    b.HasIndex("ProfileId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_payroll_employee_identifiers_profile_id_employee_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("ProfileId", "ExternalEmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_payroll_employee_identifiers_profile_id_external_employee_id")
                        .HasFilter("is_deleted = false");

                    b.ToTable("payroll_employee_identifiers", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayrollExportProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjustmentEarningCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adjustment_earning_code");

                    b.Property<int>("AmountScale")
                        .HasColumnType("integer")
                        .HasColumnName("amount_scale");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("Grouping")
                        .HasColumnType("integer")
                        .HasColumnName("grouping");

                    b.Property<int>("HoursScale")
                        .HasColumnType("integer")
                        .HasColumnName("hours_scale");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<int>("RoundingPolicy")
                        .HasColumnType("integer")
                        .HasColumnName("rounding_policy");

                    b.HasKey("Id")
                        .HasName("pk_payroll_export_profiles");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_payroll_export_profiles_client_id");

                    b.ToTable("payroll_export_profiles", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PunchChangeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeKind")
                        .HasColumnType("integer")
                        .HasColumnName("change_kind");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int?>("PunchId")
                        .HasColumnType("integer")
                        .HasColumnName("punch_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal?>("RequestedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("requested_amount");

                    b.Property<int?>("RequestedBonusKind")
                        .HasColumnType("integer")
                        .HasColumnName("requested_bonus_kind");

                    b.Property<bool?>("RequestedCountsTowardRegularRate")
                        .HasColumnType("boolean")
                        .HasColumnName("requested_counts_toward_regular_rate");

                    b.Property<decimal?>("RequestedHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("requested_hours");

                    b.Property<int?>("RequestedKind")
                        .HasColumnType("integer")
                        .HasColumnName("requested_kind");

                    b.Property<int?>("RequestedPositionId")
                        .HasColumnType("integer")
                        .HasColumnName("requested_position_id");

                    b.Property<Instant?>("RequestedPunchTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_punch_time");

                    b.Property<string>("RequestedPunchTimeZoneId")
                        .HasColumnType("text")
                        .HasColumnName("requested_punch_time_zone_id");

                    b.Property<int?>("RequestedSubtype")
                        .HasColumnType("integer")
                        .HasColumnName("requested_subtype");

                    b.Property<string>("RequesterUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<Instant?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewerUserId")
                        .HasColumnType("text")
                        .HasColumnName("reviewer_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_punch_change_requests");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_punch_change_requests_employee_id");

                    b.HasIndex("ClientId", "Status", "EmployeeId")
                        .HasDatabaseName("ix_punch_change_requests_client_id_status_employee_id");

                    b.ToTable("punch_change_requests", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PunchImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<Instant>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("ImportedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imported_by_user_id");

                    b.Property<int>("PunchCount")
                        .HasColumnType("integer")
                        .HasColumnName("punch_count");

                    b.HasKey("Id")
                        .HasName("pk_punch_import_batches");

                    b.HasIndex("ClientId", "ImportedAt")
                        .HasDatabaseName("ix_punch_import_batches_client_id_imported_at");

                    b.ToTable("punch_import_batches", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.TimecardApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approved_by_user_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<LocalDate>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<LocalDate>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<Instant?>("UnapprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unapproved_at");

                    b.Property<string>("UnapprovedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("unapproved_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_timecard_approvals");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_timecard_approvals_employee_id");

                    b.HasIndex("ClientId", "EmployeeId", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_timecard_approvals_client_id_employee_id_period_start_perio");

                    b.ToTable("timecard_approvals", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.DifferentialRule", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_differential_rules_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Model.Employee", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Model.HolidayCalendar", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_holiday_calendars_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Model.PayRules.PayRule", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_rules_clients_client_id");

                    b.HasOne("TimeCalculation.Model.HolidayCalendar", null)
                        .WithMany()
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pay_rules_holiday_calendars_holiday_calendar_id");

                    b.OwnsOne("TimeCalculation.Model.PayRules.OvertimeRule", "OvertimeRule", b1 =>
                        {
                            b1.Property<int>("PayRuleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("DailyDoubletimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("overtime_rule_daily_doubletime_threshold_hours");

                            b1.Property<decimal>("DailyOvertimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("overtime_rule_daily_overtime_threshold_hours");

                            b1.Property<bool>("HasDailyOvertime")
                                .HasColumnType("boolean")
                                .HasColumnName("overtime_rule_has_daily_overtime");

                            b1.Property<bool>("HasSeventhDayRule")
                                .HasColumnType("boolean")
                                .HasColumnName("overtime_rule_has_seventh_day_rule");

                            b1.Property<decimal>("WeeklyOvertimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("overtime_rule_weekly_overtime_threshold_hours");

                            b1.HasKey("PayRuleId");

                            b1.ToTable("pay_rules");

                            b1.WithOwner()
                                .HasForeignKey("PayRuleId")
                                .HasConstraintName("fk_pay_rules_pay_rules_id");
                        });

                    b.OwnsOne("TimeCalculation.Model.PayRules.RoundingRule", "RoundingRule", b1 =>
                        {
                            b1.Property<int>("PayRuleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("RoundingGraceMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("rounding_rule_rounding_grace_minutes");

                            b1.Property<int>("RoundingIntervalMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("rounding_rule_rounding_interval_minutes");

                            b1.Property<int>("RoundingStrategy")
                                .HasColumnType("integer")
                                .HasColumnName("rounding_rule_rounding_strategy");

                            b1.HasKey("PayRuleId");

                            b1.ToTable("pay_rules");

                            b1.WithOwner()
                                .HasForeignKey("PayRuleId")
                                .HasConstraintName("fk_pay_rules_pay_rules_id");
                        });

                    b.Navigation("OvertimeRule")
                        .IsRequired();

                    b.Navigation("RoundingRule")
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCalculation.Model.Position", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Model.Premiums.ClientPremiumPolicy", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_premium_policies_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Model.Punch", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_punches_clients_client_id");

                    b.HasOne("TimeCalculation.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_punches_employees_employee_id");

                    b.HasOne("TimeCalculation.Persistence.PunchImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_punches_punch_import_batches_import_batch_id");

                    b.HasOne("TimeCalculation.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .HasConstraintName("fk_punches_positions_position_id");

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TimeCalculation.Model.PunchAuditEntry", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_punch_audits_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.AppUser", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_users_clients_client_id");

                    b.HasOne("TimeCalculation.Model.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_users_employees_employee_id");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.ClientSettings", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_settings_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.EmployeePositionAssignmentEntity", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_position_assignments_clients_client_id");

                    b.HasOne("TimeCalculation.Model.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_position_assignments_employees_employee_id");

                    b.HasOne("TimeCalculation.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_position_assignments_positions_position_id");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayRuleAssignmentEntity", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_rule_assignments_clients_client_id");

                    b.HasOne("TimeCalculation.Model.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_rule_assignments_employees_employee_id");

                    b.HasOne("TimeCalculation.Model.PayRules.PayRule", "PayRule")
                        .WithMany()
                        .HasForeignKey("PayRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pay_rule_assignments_pay_rules_pay_rule_id");

                    b.Navigation("PayRule");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayrollEarningCodeMapping", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_earning_code_mappings_clients_client_id");

                    b.HasOne("TimeCalculation.Persistence.PayrollExportProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_earning_code_mappings_payroll_export_profiles_profi");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayrollEmployeeIdentifier", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_employee_identifiers_clients_client_id");

                    b.HasOne("TimeCalculation.Model.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_employee_identifiers_employees_employee_id");

                    b.HasOne("TimeCalculation.Persistence.PayrollExportProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_employee_identifiers_payroll_export_profiles_profil");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayrollExportProfile", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_export_profiles_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PunchChangeRequest", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_punch_change_requests_clients_client_id");

                    b.HasOne("TimeCalculation.Model.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_punch_change_requests_employees_employee_id");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PunchImportBatch", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_punch_import_batches_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.TimecardApproval", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_timecard_approvals_clients_client_id");

                    b.HasOne("TimeCalculation.Model.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_timecard_approvals_employees_employee_id");
                });
#pragma warning restore 612, 618
        }
    }
}
