// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeCalculation.Persistence;

#nullable disable

namespace TimeCalculation.Persistence.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260722165118_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeCalculation.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("HomeTimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_time_zone_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<decimal>("MinimumWage")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("minimum_wage");

                    b.Property<string>("PostNominalLetters")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_nominal_letters");

                    b.Property<string>("Salutation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_employees_client_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.PayRules.PayRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivePremiumCodes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("active_premium_codes");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<decimal>("DistanceBetweenShiftsHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("distance_between_shifts_hours");

                    b.Property<int>("ExpectedBreakLengthMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("expected_break_length_minutes");

                    b.Property<int>("ExpectedLunchLengthMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("expected_lunch_length_minutes");

                    b.Property<decimal>("MaxShiftLengthHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("max_shift_length_hours");

                    b.Property<decimal>("PunchPairResetHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("punch_pair_reset_hours");

                    b.Property<int>("ShiftDateStrategy")
                        .HasColumnType("integer")
                        .HasColumnName("shift_date_strategy");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("WorkweekStartDay")
                        .HasColumnType("integer")
                        .HasColumnName("workweek_start_day");

                    b.HasKey("Id")
                        .HasName("pk_pay_rules");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_pay_rules_client_id");

                    b.ToTable("pay_rules", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("base_rate");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_positions_client_id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Punch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<int?>("BonusKind")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_kind");

                    b.Property<bool>("CountsTowardRegularRate")
                        .HasColumnType("boolean")
                        .HasColumnName("counts_toward_regular_rate");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("DevicePunchId")
                        .HasColumnType("text")
                        .HasColumnName("device_punch_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<decimal?>("Hours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("hours");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<Instant>("PunchTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("punch_time");

                    b.Property<string>("PunchTimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("punch_time_zone_id");

                    b.Property<Instant?>("RoundedPunchTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rounded_punch_time");

                    b.Property<int?>("Subtype")
                        .HasColumnType("integer")
                        .HasColumnName("subtype");

                    b.HasKey("Id")
                        .HasName("pk_punches");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_punches_position_id");

                    b.HasIndex("EmployeeId", "PunchTime")
                        .HasDatabaseName("ix_punches_employee_id_punch_time");

                    b.HasIndex("EmployeeId", "DeviceId", "DevicePunchId")
                        .IsUnique()
                        .HasDatabaseName("ix_punches_employee_id_device_id_device_punch_id");

                    b.ToTable("punches", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.PunchAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("text")
                        .HasColumnName("previous_values");

                    b.Property<int>("PunchId")
                        .HasColumnType("integer")
                        .HasColumnName("punch_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_punch_audits");

                    b.HasIndex("PunchId")
                        .HasDatabaseName("ix_punch_audits_punch_id");

                    b.ToTable("punch_audits", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.StateMinimumWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_state_minimum_wages");

                    b.HasIndex("State", "EffectiveFrom")
                        .HasDatabaseName("ix_state_minimum_wages_state_effective_from");

                    b.ToTable("state_minimum_wages", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.EmployeePositionAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_position_assignments");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_employee_position_assignments_position_id");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("ix_employee_position_assignments_employee_id_effective_from");

                    b.ToTable("employee_position_assignments", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayRuleAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("PayRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("pay_rule_id");

                    b.HasKey("Id")
                        .HasName("pk_pay_rule_assignments");

                    b.HasIndex("PayRuleId")
                        .HasDatabaseName("ix_pay_rule_assignments_pay_rule_id");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("ix_pay_rule_assignments_employee_id_effective_from");

                    b.ToTable("pay_rule_assignments", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Employee", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Model.PayRules.PayRule", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_rules_clients_client_id");

                    b.OwnsOne("TimeCalculation.Model.PayRules.OvertimeRule", "OvertimeRule", b1 =>
                        {
                            b1.Property<int>("PayRuleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("DailyDoubletimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("overtime_rule_daily_doubletime_threshold_hours");

                            b1.Property<decimal>("DailyOvertimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("overtime_rule_daily_overtime_threshold_hours");

                            b1.Property<bool>("HasDailyOvertime")
                                .HasColumnType("boolean")
                                .HasColumnName("overtime_rule_has_daily_overtime");

                            b1.Property<bool>("HasSeventhDayRule")
                                .HasColumnType("boolean")
                                .HasColumnName("overtime_rule_has_seventh_day_rule");

                            b1.Property<decimal>("WeeklyOvertimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("overtime_rule_weekly_overtime_threshold_hours");

                            b1.HasKey("PayRuleId");

                            b1.ToTable("pay_rules");

                            b1.WithOwner()
                                .HasForeignKey("PayRuleId")
                                .HasConstraintName("fk_pay_rules_pay_rules_id");
                        });

                    b.OwnsOne("TimeCalculation.Model.PayRules.RoundingRule", "RoundingRule", b1 =>
                        {
                            b1.Property<int>("PayRuleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("RoundingGraceMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("rounding_rule_rounding_grace_minutes");

                            b1.Property<int>("RoundingIntervalMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("rounding_rule_rounding_interval_minutes");

                            b1.Property<int>("RoundingStrategy")
                                .HasColumnType("integer")
                                .HasColumnName("rounding_rule_rounding_strategy");

                            b1.HasKey("PayRuleId");

                            b1.ToTable("pay_rules");

                            b1.WithOwner()
                                .HasForeignKey("PayRuleId")
                                .HasConstraintName("fk_pay_rules_pay_rules_id");
                        });

                    b.Navigation("OvertimeRule")
                        .IsRequired();

                    b.Navigation("RoundingRule")
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCalculation.Model.Position", b =>
                {
                    b.HasOne("TimeCalculation.Model.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_clients_client_id");
                });

            modelBuilder.Entity("TimeCalculation.Model.Punch", b =>
                {
                    b.HasOne("TimeCalculation.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_punches_employees_employee_id");

                    b.HasOne("TimeCalculation.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .HasConstraintName("fk_punches_positions_position_id");

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.EmployeePositionAssignmentEntity", b =>
                {
                    b.HasOne("TimeCalculation.Model.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_position_assignments_employees_employee_id");

                    b.HasOne("TimeCalculation.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_position_assignments_positions_position_id");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayRuleAssignmentEntity", b =>
                {
                    b.HasOne("TimeCalculation.Model.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_rule_assignments_employees_employee_id");

                    b.HasOne("TimeCalculation.Model.PayRules.PayRule", "PayRule")
                        .WithMany()
                        .HasForeignKey("PayRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pay_rule_assignments_pay_rules_pay_rule_id");

                    b.Navigation("PayRule");
                });
#pragma warning restore 612, 618
        }
    }
}
