// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeCalculation.Persistence;

#nullable disable

namespace TimeCalculation.Persistence.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260722164423_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeCalculation.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeTimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MinimumWage")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("PostNominalLetters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salutation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.PayRules.PayRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivePremiumCodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DistanceBetweenShiftsHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("ExpectedBreakLengthMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedLunchLengthMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxShiftLengthHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("PunchPairResetHours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("ShiftDateStrategy")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("WorkweekStartDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("pay_rules", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.Punch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<int?>("BonusKind")
                        .HasColumnType("integer");

                    b.Property<bool>("CountsTowardRegularRate")
                        .HasColumnType("boolean");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DevicePunchId")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Hours")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer");

                    b.Property<Instant>("PunchTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PunchTimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant?>("RoundedPunchTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Subtype")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("EmployeeId", "PunchTime");

                    b.HasIndex("EmployeeId", "DeviceId", "DevicePunchId")
                        .IsUnique();

                    b.ToTable("punches", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.PunchAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("text");

                    b.Property<int>("PunchId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PunchId");

                    b.ToTable("punch_audits", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.StateMinimumWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("State", "EffectiveFrom");

                    b.ToTable("state_minimum_wages", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.EmployeePositionAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("EmployeeId", "EffectiveFrom");

                    b.ToTable("employee_position_assignments", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayRuleAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<LocalDate>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<LocalDate?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("PayRuleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PayRuleId");

                    b.HasIndex("EmployeeId", "EffectiveFrom");

                    b.ToTable("pay_rule_assignments", (string)null);
                });

            modelBuilder.Entity("TimeCalculation.Model.PayRules.PayRule", b =>
                {
                    b.OwnsOne("TimeCalculation.Model.PayRules.OvertimeRule", "OvertimeRule", b1 =>
                        {
                            b1.Property<int>("PayRuleId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("DailyDoubletimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)");

                            b1.Property<decimal>("DailyOvertimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)");

                            b1.Property<bool>("HasDailyOvertime")
                                .HasColumnType("boolean");

                            b1.Property<bool>("HasSeventhDayRule")
                                .HasColumnType("boolean");

                            b1.Property<decimal>("WeeklyOvertimeThresholdHours")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)");

                            b1.HasKey("PayRuleId");

                            b1.ToTable("pay_rules");

                            b1.WithOwner()
                                .HasForeignKey("PayRuleId");
                        });

                    b.OwnsOne("TimeCalculation.Model.PayRules.RoundingRule", "RoundingRule", b1 =>
                        {
                            b1.Property<int>("PayRuleId")
                                .HasColumnType("integer");

                            b1.Property<int>("RoundingGraceMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("RoundingIntervalMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("RoundingStrategy")
                                .HasColumnType("integer");

                            b1.HasKey("PayRuleId");

                            b1.ToTable("pay_rules");

                            b1.WithOwner()
                                .HasForeignKey("PayRuleId");
                        });

                    b.Navigation("OvertimeRule")
                        .IsRequired();

                    b.Navigation("RoundingRule")
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCalculation.Model.Punch", b =>
                {
                    b.HasOne("TimeCalculation.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeCalculation.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId");

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.EmployeePositionAssignmentEntity", b =>
                {
                    b.HasOne("TimeCalculation.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TimeCalculation.Persistence.PayRuleAssignmentEntity", b =>
                {
                    b.HasOne("TimeCalculation.Model.PayRules.PayRule", "PayRule")
                        .WithMany()
                        .HasForeignKey("PayRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayRule");
                });
#pragma warning restore 612, 618
        }
    }
}
