/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListClients"];
        put?: never;
        post: operations["CreateClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetClient"];
        put: operations["UpdateClient"];
        post?: never;
        delete: operations["DeleteClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListEmployees"];
        put?: never;
        post: operations["CreateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEmployee"];
        put: operations["UpdateEmployee"];
        post?: never;
        delete: operations["DeleteEmployee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListPositions"];
        put?: never;
        post: operations["CreatePosition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPosition"];
        put: operations["UpdatePosition"];
        post?: never;
        delete: operations["DeletePosition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payrules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListPayRules"];
        put?: never;
        post: operations["CreatePayRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payrules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPayRule"];
        put: operations["UpdatePayRule"];
        post?: never;
        delete: operations["DeletePayRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/punches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreatePunch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/premium-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPremiumRuleMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        AppRole: "SystemAdmin" | "ClientAdmin" | "Supervisor" | "Employee";
        /** @enum {unknown} */
        BonusKind: "Discretionary" | "NonDiscretionary" | null;
        ClientResponse: {
            /** Format: int32 */
            id: number | string;
            name: string;
            createdBy: string;
            /** Format: date-time */
            createdDate: string;
        };
        CreateClientRequest: {
            name: string;
        };
        CreateEmployeeRequest: {
            /** Format: int32 */
            clientId: number | string;
            firstName: string;
            middleName?: null | string;
            lastName: string;
            salutation?: null | string;
            postNominalLetters?: null | string;
            /** Format: double */
            minimumWage: number | string;
            homeTimeZoneId?: null | string;
            state?: null | string;
        };
        CreatePayRuleRequest: {
            /** Format: int32 */
            clientId: number | string;
            name: string;
            description?: null | string;
            templateCode?: null | string;
            /** Format: int32 */
            templateVersion?: null | number | string;
            /** Format: double */
            punchPairResetHours?: null | number | string;
            /** Format: double */
            maxShiftLengthHours?: null | number | string;
            /** Format: double */
            distanceBetweenShiftsHours?: null | number | string;
            /** Format: int32 */
            expectedBreakLengthMinutes?: null | number | string;
            /** Format: int32 */
            expectedLunchLengthMinutes?: null | number | string;
            roundingStrategy?: null | components["schemas"]["RoundingStrategy"];
            /** Format: int32 */
            roundingIntervalMinutes?: null | number | string;
            /** Format: int32 */
            roundingGraceMinutes?: null | number | string;
            shiftDateStrategy?: null | components["schemas"]["ShiftDateStrategy"];
            workweekStartDay?: null | components["schemas"]["IsoDayOfWeek"];
            activePremiumCodes?: null | string[];
            activeDifferentialCodes?: null | string[];
            /** Format: double */
            weeklyOvertimeThresholdHours?: null | number | string;
            hasDailyOvertime?: null | boolean;
            /** Format: double */
            dailyOvertimeThresholdHours?: null | number | string;
            /** Format: double */
            dailyDoubletimeThresholdHours?: null | number | string;
            hasSeventhDayRule?: null | boolean;
        };
        CreatePositionRequest: {
            /** Format: int32 */
            clientId: number | string;
            code: string;
            name: string;
            /** Format: double */
            baseRate: number | string;
        };
        CreatePunchRequest: {
            /** Format: int32 */
            employeeId: number | string;
            punchTime: components["schemas"]["Instant"];
            punchTimeZoneId?: null | string;
            kind: components["schemas"]["PunchKind"];
            subtype?: null | components["schemas"]["PunchSubtype"];
            /** Format: int32 */
            positionId?: null | number | string;
            /** Format: double */
            amount?: null | number | string;
            /** Format: double */
            hours?: null | number | string;
            bonusKind?: null | components["schemas"]["BonusKind"];
            countsTowardRegularRate?: boolean;
            deviceId?: null | string;
            devicePunchId?: null | string;
        };
        CreateUserRequest: {
            email: string;
            /** Format: int32 */
            clientId?: null | number | string;
            /** Format: int32 */
            employeeId?: null | number | string;
            displayName: string;
            role: components["schemas"]["AppRole"];
        };
        Employee: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            clientId?: number | string;
            firstName?: string;
            middleName?: string;
            lastName?: string;
            salutation?: string;
            postNominalLetters?: string;
            /** Format: double */
            minimumWage?: number | string;
            homeTimeZoneId?: string;
            state?: string;
            isDeleted?: boolean;
        };
        EmployeeResponse: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            clientId: number | string;
            firstName: string;
            middleName: string;
            lastName: string;
            salutation: string;
            postNominalLetters: string;
            /** Format: double */
            minimumWage: number | string;
            homeTimeZoneId: string;
            state: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        Instant: unknown;
        /** @enum {unknown} */
        IsoDayOfWeek: "None" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
        LocalDate: unknown;
        PagedResultOfClientResponse: {
            items: components["schemas"]["ClientResponse"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PagedResultOfEmployeeResponse: {
            items: components["schemas"]["EmployeeResponse"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PagedResultOfPayRuleResponse: {
            items: components["schemas"]["PayRuleResponse"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PagedResultOfPositionResponse: {
            items: components["schemas"]["PositionResponse"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PayRuleResponse: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            clientId: number | string;
            name: string;
            description?: null | string;
            templateCode?: null | string;
            /** Format: int32 */
            templateVersion?: null | number | string;
            /** Format: int32 */
            ruleFamilyId: number | string;
            /** Format: int32 */
            version: number | string;
            status: components["schemas"]["PayRuleStatus"];
            effectiveFrom?: null | components["schemas"]["LocalDate"];
            effectiveTo?: null | components["schemas"]["LocalDate"];
            /** Format: double */
            punchPairResetHours: number | string;
            /** Format: double */
            maxShiftLengthHours: number | string;
            /** Format: double */
            distanceBetweenShiftsHours: number | string;
            /** Format: int32 */
            expectedBreakLengthMinutes: number | string;
            /** Format: int32 */
            expectedLunchLengthMinutes: number | string;
            roundingStrategy: components["schemas"]["RoundingStrategy"];
            /** Format: int32 */
            roundingIntervalMinutes: number | string;
            /** Format: int32 */
            roundingGraceMinutes: number | string;
            shiftDateStrategy: components["schemas"]["ShiftDateStrategy"];
            workweekStartDay: components["schemas"]["IsoDayOfWeek"];
            activePremiumCodes: string[];
            activeDifferentialCodes: string[];
            /** Format: double */
            weeklyOvertimeThresholdHours: number | string;
            hasDailyOvertime: boolean;
            /** Format: double */
            dailyOvertimeThresholdHours: number | string;
            /** Format: double */
            dailyDoubletimeThresholdHours: number | string;
            hasSeventhDayRule: boolean;
        };
        /** @enum {unknown} */
        PayRuleStatus: "Draft" | "Active" | "Superseded";
        Position: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            clientId?: number | string;
            code?: string;
            name?: string;
            /** Format: double */
            baseRate?: number | string;
            isDeleted?: boolean;
        };
        PositionResponse: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            clientId: number | string;
            code: string;
            name: string;
            /** Format: double */
            baseRate: number | string;
        };
        Punch: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            clientId?: number | string;
            /** Format: int32 */
            employeeId?: number | string;
            punchTime?: components["schemas"]["Instant"];
            roundedPunchTime?: null | components["schemas"]["Instant"];
            punchTimeZoneId?: string;
            kind?: components["schemas"]["PunchKind"];
            subtype?: null | components["schemas"]["PunchSubtype"];
            /** Format: int32 */
            positionId?: null | number | string;
            /** Format: double */
            amount?: null | number | string;
            /** Format: double */
            hours?: null | number | string;
            bonusKind?: null | components["schemas"]["BonusKind"];
            countsTowardRegularRate?: boolean;
            createdAt?: components["schemas"]["Instant"];
            createdBy?: string;
            isDeleted?: boolean;
            deviceId?: null | string;
            devicePunchId?: null | string;
            employee?: null | components["schemas"]["Employee"];
            position?: null | components["schemas"]["Position"];
            effectiveTime?: components["schemas"]["Instant"];
            isClockPunch?: boolean;
            isFixedEntry?: boolean;
        };
        /** @enum {unknown} */
        PunchKind: "In" | "Out" | "FixedDollar" | "FixedHours";
        /** @enum {unknown} */
        PunchSubtype: "None" | "Break" | "Lunch" | null;
        /** @enum {unknown} */
        RoundingStrategy: "None" | "NearestInterval" | "IntervalWithGrace";
        /** @enum {unknown} */
        ShiftDateStrategy: "FirstPunchLocalDate" | "LastPunchLocalDate" | "MajorityHoursLocalDate" | "SplitAtMidnight";
        UpdateClientRequest: {
            name: string;
        };
        UpdateEmployeeRequest: {
            firstName: string;
            middleName?: null | string;
            lastName: string;
            salutation?: null | string;
            postNominalLetters?: null | string;
            /** Format: double */
            minimumWage: number | string;
            homeTimeZoneId?: null | string;
            state?: null | string;
        };
        UpdatePayRuleRequest: {
            name?: null | string;
            description?: null | string;
            templateCode?: null | string;
            /** Format: int32 */
            templateVersion?: null | number | string;
            /** Format: double */
            punchPairResetHours?: null | number | string;
            /** Format: double */
            maxShiftLengthHours?: null | number | string;
            /** Format: double */
            distanceBetweenShiftsHours?: null | number | string;
            /** Format: int32 */
            expectedBreakLengthMinutes?: null | number | string;
            /** Format: int32 */
            expectedLunchLengthMinutes?: null | number | string;
            roundingStrategy?: null | components["schemas"]["RoundingStrategy"];
            /** Format: int32 */
            roundingIntervalMinutes?: null | number | string;
            /** Format: int32 */
            roundingGraceMinutes?: null | number | string;
            shiftDateStrategy?: null | components["schemas"]["ShiftDateStrategy"];
            workweekStartDay?: null | components["schemas"]["IsoDayOfWeek"];
            activePremiumCodes?: null | string[];
            activeDifferentialCodes?: null | string[];
            /** Format: double */
            weeklyOvertimeThresholdHours?: null | number | string;
            hasDailyOvertime?: null | boolean;
            /** Format: double */
            dailyOvertimeThresholdHours?: null | number | string;
            /** Format: double */
            dailyDoubletimeThresholdHours?: null | number | string;
            hasSeventhDayRule?: null | boolean;
        };
        UpdatePositionRequest: {
            code: string;
            name: string;
            /** Format: double */
            baseRate: number | string;
        };
        UserResponse: {
            cognitoSub: string;
            /** Format: int32 */
            clientId?: null | number | string;
            /** Format: int32 */
            employeeId?: null | number | string;
            displayName: string;
            role: components["schemas"]["AppRole"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListClients: {
        parameters: {
            query?: {
                search?: string;
                Page?: number | string;
                PageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfClientResponse"];
                };
            };
        };
    };
    CreateClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
        };
    };
    UpdateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListEmployees: {
        parameters: {
            query: {
                clientId: number | string;
                search?: string;
                Page?: number | string;
                PageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfEmployeeResponse"];
                };
            };
        };
    };
    CreateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"];
                };
            };
        };
    };
    UpdateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListPositions: {
        parameters: {
            query: {
                clientId: number | string;
                search?: string;
                Page?: number | string;
                PageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfPositionResponse"];
                };
            };
        };
    };
    CreatePosition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePositionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetPosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"];
                };
            };
        };
    };
    UpdatePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePositionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeletePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListPayRules: {
        parameters: {
            query: {
                clientId: number | string;
                status?: components["schemas"]["PayRuleStatus"];
                Page?: number | string;
                PageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfPayRuleResponse"];
                };
            };
        };
    };
    CreatePayRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePayRuleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayRuleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetPayRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayRuleResponse"];
                };
            };
        };
    };
    UpdatePayRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePayRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayRuleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeletePayRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreatePunch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePunchRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Punch"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetPremiumRuleMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
}
